# Generated by Django 5.0.6 on 2024-06-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AdminId', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=18)),
            ],
        ),
    ]
