# Generated by Django 5.0.6 on 2024-06-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('TransGender', 'TransGender')], max_length=20, verbose_name='Gender')),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='images/')),
                ('password', models.CharField(max_length=15)),
            ],
        ),
    ]
