# Generated by Django 5.0.6 on 2024-06-22 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientregistration',
            name='DOB',
            field=models.DateField(default=datetime.date(2024, 6, 23)),
        ),
    ]
