# Generated by Django 5.0.6 on 2024-06-25 15:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_patientregistration_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientregistration',
            name='DOB',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Apointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blood_Group', models.CharField(max_length=5)),
                ('Disease', models.CharField(default='unknown', max_length=10)),
                ('patients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patientregistration')),
            ],
        ),
    ]
