# Generated by Django 5.0.6 on 2024-06-25 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_alter_patientregistration_dob_apointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apointment',
            old_name='patients',
            new_name='Name',
        ),
    ]
