# Generated by Django 5.0.6 on 2024-06-24 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('DoctorId', models.CharField(max_length=10)),
                ('DOJ', models.DateField(default=datetime.date(2024, 6, 24))),
                ('Gender', models.CharField(max_length=15)),
                ('Speciality', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=18)),
            ],
        ),
    ]
