# Generated by Django 5.0.6 on 2024-06-25 15:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='DOJ',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
